opentelemetry-kube-stack:
  crds:
    installPrometheus: false

  collectors:
    daemon:
      enabled: false  

  kubeStateMetrics:
    enabled: true

  kube-state-metrics:
    metricLabelsAllowlist:
      - nodes=[*]
