{{- range $key, $value := .Values.collectors }}
  {{- range $value }}
{{- if .enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    collectorMode: {{ $key }}
    {{- include "otel.labels" $ | nindent 4 }}
spec:
  managementState: {{ .managed | default managed }}
{{- end }}
{{- end }}
{{- end }}
