{{- range $key, $value := .Values.collectors }}
  {{- range $value }}
{{- if .enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {{ .serviceAccount.annotations | toYaml }}
  name: {{ template "otel.collector.serviceAccountName" . }}
  namespace: {{ $.Values.namespace }}
{{- end }}
{{- end }}
{{- end }}
