opentelemetry-kube-stack:
  crds:
    installPrometheus: false
  
  kubernetesServiceMonitors:
    enabled: false

  kubeApiServer:
    enabled: false

  kubelet:
    enabled: false
    serviceMonitor:
      https: false
    
  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler: 
    enabled: false

  kubeProxy:
    enabled: false

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: true

  defaultCRConfig:
    config:
      exporters:
        otlphttp/logs:
          endpoint: http://loki-gateway.monitoring.svc.cluster.local:80/otlp
          tls:
            insecure: true
        otlphttp/metrics:
          endpoint: http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/otlp
          tls:
            insecure: true

  collectors:
    daemon:
      enabled: false
    otel-daemon:
      enabled: true
      name: otel-daemon
      mode: daemonset
      prometheusCR:
        enabled: true
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      presets:
        logsCollection:
          enabled: true    
        kubernetesAttributes:
          enabled: true
        hostMetrics:
          enabled: true
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi        
      config:
        exporters:
          debug: {}
        processors:
          resource/hostname:
            attributes:
            - action: insert
              from_attribute: k8s.node.name
              key: host.name
          resourcedetection/env:
            detectors:
            - env
          batch:
            send_batch_size: 1000
            timeout: 1s
            send_batch_max_size: 1500
        service:
          pipelines:
            logs:
              processors:
                - k8sattributes
                - resourcedetection/env
                - resource/hostname
                - batch
              exporters:
                #- debug
                - otlphttp/logs
            metrics:
              receivers:
                - hostmetrics
              processors:
                - k8sattributes
                - resourcedetection/env
                - resource/hostname
                - batch
              exporters:
                - debug
                - otlphttp/metrics
            

