apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nscubed-api-gateway-cert
  namespace: kube-system # Or the namespace where you'll run your test app
spec:
  secretName: nscubed-gateway-api-tls-secret # Cert-manager will store the signed cert and key here
  dnsNames:
  - "*.nscubed.lan" # Replace with your hostname
  issuerRef:
    name: nscubed-cluster-issuer # The name of your ClusterIssuer
    kind: ClusterIssuer # This must be specified as ClusterIssuer
